CREATE TABLE LineItems
(
OrderID INT,
BagelID INT,
QUANTITY INT,
CONSTRAINT PK_LineItems PRIMARY KEY (BagelOrderID, BagleID),
CONSTRAINT FK_LineItems_Donut_3NF FOREIGN KEY (DonutID) REFERENCES Donuts_3NF (DonutID),
CONSTRAINT FK_LineItems_Order_3NF FOREIGN KEY (OrderID) REFERENCES Orders_3NF (OrderID)
);
